services:
  - type: web
    name: fuel-route-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fuel_route_api.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-render-app-url.onrender.com"